version: "3"

volumes:
  code:

services:
  # Nginx
  nginx:
    build: nginx
    container_name: nginx
    working_dir: /var/www
    volumes:
      - code:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      app-network:
        aliases:
          - gentle-front.loc

  # PHP
  php-fpm:
    build: php-fpm
    container_name: php-fpm
    working_dir: /var/www
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - code:/var/www
      - ./php-fpm/php-dev.ini:/usr/local/etc/php/php.ini

    networks:
      - app-network

  # PHP for NICE module. NICE module doesn't support M1
  php-fpm-x86_64:
    build: php-fpm-x86_64
    container_name: php-fpm-x86_64
    working_dir: /var/www
    platform: linux/x86_64
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - code:/var/www
      - ./php-fpm/php-dev.ini:/usr/local/etc/php/php.ini

    networks:
      - app-network

  # MySQL
  mysql:
    image: mysql/mysql-server:8.0.26
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - app-network

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

# Set up Mutagen synchronization and forwarding.
x-mutagen:
  sync:
    analysis:
      alpha: "./project"
      beta: "volume://code"
      mode: "two-way-resolved"
      ignore:
        vcs: true
        paths:
          - "/**/.idea"
          - "/**/generated"
          - "/**/session"
      permissions:
        defaultOwner: id:501
        defaultFileMode: 666
        defaultDirectoryMode: 755
